name: Deploy Workflows to Production

permissions:
  contents: write
  issues: write

on:
  workflow_dispatch:
    inputs:
      workflows:
        description: 'Workflow base names to deploy (comma-separated)'
        required: true
      skip_backup:
        description: 'Skip backup creation'
        required: false
        default: false
        type: boolean
      custom_backup_name:
        description: 'Custom backup name (optional)'
        required: false
        default: ''

jobs:
  approve-production-deployment:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Manual approval required
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: ${{ vars.PRODUCTION_APPROVERS }}
          minimum-approvals: 1
          issue-title: "🚀 Production Deployment Approval: ${{ github.event.inputs.workflows }}"
          issue-body: |
            ## Production Workflow Deployment Request

            **Workflows to deploy:** ${{ github.event.inputs.workflows }}
            **Requested by:** ${{ github.actor }}
            **Skip backup:** ${{ github.event.inputs.skip_backup }}

            ### Pre-deployment Checklist
            - [ ] Dev workflows have been tested
            - [ ] No critical issues identified
            - [ ] Stakeholders notified

            **⚠️ This will update production workflows. Please review carefully.**

  deploy-to-production:
    runs-on: ubuntu-latest
    needs: approve-production-deployment

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Inject API key into existing config
        run: |
          jq --arg key "${{ secrets.N8N_API_KEY }}" '.n8n.apiKey = $key' config/n8n-config.json > tmp.json && mv tmp.json config/n8n-config.json

      - name: Create automatic backup
        if: github.event.inputs.skip_backup != 'true'
        run: |
          echo "💾 Creating automatic backup before deployment..."

          if [[ -n "${{ github.event.inputs.custom_backup_name }}" ]]; then
            backup_name="pre_deploy_${{ github.event.inputs.custom_backup_name }}_$(date +%Y%m%d_%H%M%S)"
          else
            backup_name="pre_deploy_auto_$(date +%Y%m%d_%H%M%S)"
          fi

          node scripts/manage-workflows.js backup prod "$backup_name"
          echo "✅ Backup created: $backup_name"
          echo "BACKUP_NAME=$backup_name" >> $GITHUB_ENV

      - name: Validate workflows before deployment
        run: |
          echo "🔍 Validating workflows before production deployment..."

          # Parse workflow names
          IFS=',' read -ra WORKFLOWS <<< "${{ github.event.inputs.workflows }}"

          for workflow in "${WORKFLOWS[@]}"; do
            workflow=$(echo "$workflow" | xargs) # trim whitespace
            echo "Validating dev workflow: ${workflow}-dev"

            # Add validation logic here
            # For now, just check if dev version exists
            node -e "
              const manager = require('./scripts/manage-workflows.js');
              const m = new manager();
              m.getAllWorkflows().then(workflows => {
                const devWorkflow = workflows.find(w => w.name === '${workflow}-dev');
                if (!devWorkflow) {
                  console.error('❌ Dev workflow not found: ${workflow}-dev');
                  process.exit(1);
                }
                console.log('✅ Found dev workflow: ${workflow}-dev');
              });
            "
          done

      - name: Deploy workflows to production
        run: |
          echo "🚀 Deploying workflows to production..."

          # Parse and deploy each workflow
          IFS=',' read -ra WORKFLOWS <<< "${{ github.event.inputs.workflows }}"

          for workflow in "${WORKFLOWS[@]}"; do
            workflow=$(echo "$workflow" | xargs) # trim whitespace
            echo "Deploying: $workflow"
            node scripts/manage-workflows.js deploy "$workflow"
          done

      - name: Post-deployment verification
        run: |
          echo "🔍 Verifying production deployment..."

          # Check that all workflows were deployed successfully
          IFS=',' read -ra WORKFLOWS <<< "${{ github.event.inputs.workflows }}"

          for workflow in "${WORKFLOWS[@]}"; do
            workflow=$(echo "$workflow" | xargs)
            echo "Checking production workflow: ${workflow}-prod"

            node -e "
              const manager = require('./scripts/manage-workflows.js');
              const m = new manager();
              m.getAllWorkflows().then(workflows => {
                const prodWorkflow = workflows.find(w => w.name === '${workflow}-prod');
                if (!prodWorkflow) {
                  console.error('❌ Production workflow not found after deployment: ${workflow}-prod');
                  process.exit(1);
                }
                console.log('✅ Verified production workflow: ${workflow}-prod');
              });
            "
          done

      - name: Create deployment summary with backup info
        run: |
          echo "## Production Deployment Summary" > deployment-summary.md
          echo "" >> deployment-summary.md
          echo "**Deployed workflows:** ${{ github.event.inputs.workflows }}" >> deployment-summary.md
          echo "**Approved by:** Production approvers" >> deployment-summary.md
          echo "**Deployed by:** ${{ github.actor }}" >> deployment-summary.md
          echo "**Date:** $(date -u)" >> deployment-summary.md
          echo "**Backup created:** ${{ github.event.inputs.skip_backup != 'true' && 'Yes' || 'No' }}" >> deployment-summary.md

          if [[ "${{ github.event.inputs.skip_backup }}" != "true" ]]; then
          echo "**Backup name:** $BACKUP_NAME" >> deployment-summary.md
          echo "" >> deployment-summary.md
          echo "### Rollback Instructions" >> deployment-summary.md
          echo "If issues occur, you can restore from the backup:" >> deployment-summary.md
          echo '```bash' >> deployment-summary.md
          echo "npm run backup:restore $BACKUP_NAME" >> deployment-summary.md
          echo '```' >> deployment-summary.md
          echo "Or use GitHub Actions: Emergency Restore workflow" >> deployment-summary.md
          fi

          echo "" >> deployment-summary.md
          echo "**⚠️ Important:** All deployed workflows are imported as INACTIVE for safety." >> deployment-summary.md
          echo "Please manually activate them in n8n after verification." >> deployment-summary.md

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          if [[ -n "$(git status --porcelain)" ]]; then
            git add workflows/backups/
            git commit -m "deploy: ${{ github.event.inputs.workflows }} to production with backup"
            git push
          fi

      - name: Upload deployment artifacts
        uses: actions/upload-artifact@v4
        with:
          name: production-deployment-${{ github.run_number }}
          path: |
            workflows/backups/
            deployment-summary.md

#      - name: Notify production deployment
#        uses: 8398a7/action-slack@v3
#        with:
#          status: ${{ job.status }}
#          channel: '#prod-deployments'
#          text: |
#            🚀 PRODUCTION DEPLOYMENT ${{ job.status }}!
#
#            Workflows: ${{ github.event.inputs.workflows }}
#            Deployed by: ${{ github.actor }}
#          webhook_url: ${{ secrets.SLACK_WEBHOOK }}
#        if: always()
