name: Commit development workflows

permissions:
  contents: write
  issues: write

on:
  workflow_dispatch:
    inputs:
      workflows:
        description: 'Workflow base names to export (comma-separated, leave empty for all)'
        required: false
        default: ''

jobs:
  export-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Inject API key into existing config
        run: |
          jq --arg key "${{ secrets.N8N_API_KEY }}" '.n8n.apiKey = $key' config/n8n-config.json > tmp.json && mv tmp.json config/n8n-config.json

      - name: Export development workflows
        run: |
          if [[ -n "${{ github.event.inputs.workflows }}" ]]; then
            # Export specific workflows using the new export manager
            echo "🎯 Exporting specific workflows: ${{ github.event.inputs.workflows }}"
            node scripts/export-manager.js export-specific dev "${{ github.event.inputs.workflows }}"
          else
            # Export all managed dev workflows
            echo "📤 Exporting all managed dev workflows"
            node scripts/export-manager.js export dev
          fi

      - name: Commit exported workflows
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          if [[ -n "$(git status --porcelain)" ]]; then
            git add workflows/ logs/
            git commit -m "chore: export dev workflows $(date -u +%Y-%m-%d) - ${{ github.event.inputs.workflows || 'all workflows' }}"
            git push
            echo "✅ Changes committed and pushed"
          else
            echo "ℹ️ No changes to commit"
          fi

      - name: Create enhanced export summary
        run: |
          echo "📊 Creating enhanced export summary"
          
          # The export-summary.md should already be created by the export manager
          if [[ -f "export-summary.md" ]]; then
            echo "✅ Export summary already created by export manager"
          else
            echo "⚠️ Creating fallback export summary"
            echo "## Development Workflow Export Summary" > export-summary.md
            echo "" >> export-summary.md
            echo "**Triggered by:** ${{ github.actor }}" >> export-summary.md
            echo "**Date:** $(date -u)" >> export-summary.md
            echo "**Specific workflows:** ${{ github.event.inputs.workflows || 'All managed workflows' }}" >> export-summary.md
            echo "" >> export-summary.md
            echo "**Status:** Export completed" >> export-summary.md
          fi

      - name: Display export results
        run: |
          echo "📋 Export Results:"
          echo "=================="
          
          if [[ -f "export-summary.json" ]]; then
            echo "📊 Summary from export-summary.json:"
            node -e "
              const summary = JSON.parse(require('fs').readFileSync('export-summary.json', 'utf8'));
              console.log('✅ Export Status:', summary.success ? 'Success' : 'Failed');
              console.log('📊 Total workflows:', summary.totalWorkflows);
              console.log('✅ Successful:', summary.successful);
              console.log('❌ Failed:', summary.failed);
              console.log('📝 Export type:', summary.exportType);
          
              if (summary.successfulWorkflows.length > 0) {
                console.log('\\n📤 Successfully exported:');
                summary.successfulWorkflows.forEach(w => {
                  console.log('  -', w.baseName, '(' + w.nodeCount + ' nodes)');
                });
              }
          
              if (summary.failedWorkflows.length > 0) {
                console.log('\\n❌ Failed exports:');
                summary.failedWorkflows.forEach(w => {
                  console.log('  -', w.name, ':', w.error);
                });
              }
            "
          else
            echo "⚠️ No detailed summary available"
          fi

      - name: Upload export artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dev-workflows-export-${{ github.run_number }}
          path: |
            workflows/
            logs/
            export-summary.md
            export-summary.json
          retention-days: 30
