name: 4. Production Backup (scheduled 1 per day)

permissions:
  contents: write
  issues: write

on:
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  daily-backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Inject API key into existing config
        run: |
          jq --arg key "${{ secrets.N8N_API_KEY }}" '.n8n.apiKey = $key' config/n8n-config.json > tmp.json && mv tmp.json config/n8n-config.json

      - name: Create daily backup
        id: backup
        run: |
          BACKUP_DATE=$(date +%Y%m%d_%H%M%S)
          BACKUP_NAME="daily_auto_$BACKUP_DATE"
          echo "backup_name=$BACKUP_NAME" >> $GITHUB_OUTPUT
          echo "backup_date=$(date +%Y%m%d)" >> $GITHUB_OUTPUT
          node scripts/manage-workflows.js backup prod "$BACKUP_NAME"

      - name: Save backup to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: prod-backup-${{ steps.backup.outputs.backup_date }}
          path: backups/${{ steps.backup.outputs.backup_name }}
